{% set name = "snax" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: 7dccf3d25c43501d4461fa75f82155a32c69bf9334cb3387d27232593a716cac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - setuptools-scm >=3.4
    - wheel
    - pip
  run:
    - gstreamer
    - gst-plugins-base
    - gstlal >=1.10.0
    - gstlal-ugly >=1.10.0
    - h5py
    - jinja2
    - ligo-scald >=0.8
    - ligo-segments
    - numpy
    - pluggy
    - python >=3.6
    - python-lal
    - python-ligo-lw
    - pygobject
    - scipy

test:
  imports:
    - snax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.ligo.org/snax/snax
  doc_url: https://docs.ligo.org/snax/snax
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Stream-based Noise Acquisition and eXtraction toolkit

extra:
  recipe-maintainers:
    - myNameIsPatrick
